global using System;
global using System.Buffers;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection.Metadata;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Threading;
global using PwshSpectreConsole.Extensions;
global using PwshSpectreConsole.Models;
global using PwshSpectreConsole.Render;
global using PwshSpectreConsole.Terminal;
global using PwshSpectreConsole.Utilities;
global using SixLabors.ImageSharp;
global using SixLabors.ImageSharp.PixelFormats;
global using SixLabors.ImageSharp.Processing;
global using SixLabors.ImageSharp.Processing.Processors.Quantization;
global using SixLabors.ImageSharp.Processing.Processors.Transforms;
global using Spectre.Console;
global using Spectre.Console.Rendering;
global using Color = Spectre.Console.Color;
global using SixColor = SixLabors.ImageSharp.Color;
global using SixImage = SixLabors.ImageSharp.Image;
