name: PSGallery Publish
env:
 PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  publish-to-psgallery:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Deploy Package
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          & ./PwshSpectreConsole/Build.ps1
          Publish-Module -Path "./PwshSpectreConsole/" -NugetApiKey $env:PSGALLERY_API_KEY
