name: Publish to PSGallery
on:
  push:
    branches:
      - main
      - prerelease

permissions:
  contents: write

jobs:
  publish-to-psgallery:
    name: Publish
    environment: prod
    env:
      PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'ShaunLawrie'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PIPELINE_PAT }}
      - name: Version Bump and Publish
        uses: ./.github/actions/version-bump-and-publish
        with:
          psgallery-api-token: ${{ secrets.PSGALLERY_API_KEY }}
          gh-token: ${{ secrets.PIPELINE_PAT }}
          publish-type: stable
      - name: Upload Snapshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Snapshots
          path: PwshSpectreConsole.Tests/@snapshots/*.txt

  publish-prerelease-to-psgallery:
    name: Publish Prerelease
    environment: prod
    env:
      PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prerelease' && github.repository_owner == 'ShaunLawrie'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PIPELINE_PAT }}
      - name: Version Bump and Publish
        uses: ./.github/actions/version-bump-and-publish
        with:
          psgallery-api-token: ${{ secrets.PSGALLERY_API_KEY }}
          gh-token: ${{ secrets.PIPELINE_PAT }}
          publish-type: prerelease
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "./PwshSpectreConsole.Docs/dist"
          command: pages deploy . --project-name pwshspectreconsole --commit-dirty=true --branch=prerelease
      - name: Upload Snapshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Snapshots
          path: PwshSpectreConsole.Tests/@snapshots/*.txt

  check-jobs:
    name: Check Jobs
    runs-on: ubuntu-latest
    needs: [ publish-to-psgallery, publish-prerelease-to-psgallery ]
    if: github.repository_owner == 'ShaunLawrie'
    steps:
      - name: Verify no jobs failed
        run: exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
      - name: Verify at least one job succeeded
        run: exit ${{ contains(needs.*.result, 'success') && 0 || 1 }}